export const SET_OUTBOUND_IDENTIFICATION_LISTS =
  'app/OutboundAniSelect/SET_OUTBOUND_IDENTIFICATION_LISTS';
export const SELECT_OUTBOUND_IDENTIFICATION =
  'app/OutboundAniSelect/SELECT_OUTBOUND_IDENTIFICATION';
export const FETCH_OUTBOUND_IDENTIFIER_LISTS =
  'app/OutboundAniSelect/FETCH_OUTBOUND_IDENTIFIER_LISTS';
