// Redux constants

export const SET_RESOURCE_CAPACITY = 'app/TransferMenu/SET_RESOURCE_CAPACITY';
export const SET_USERS = 'app/TransferMenu/SET_USERS';
export const GET_AND_SET_TRANSFER_LISTS = 'app/TransferMenu/SET_TRANSFER_LISTS';
export const SET_QUEUES_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_QUEUES_LIST_VISIBLE_STATE';
export const SET_AGENTS_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_AGENTS_LIST_VISIBLE_STATE';
export const SET_TRANSFER_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_TRANSFER_LIST_VISIBLE_STATE';

// Saga constants
export const SET_TRANSFER_LISTS = 'app/TransferMenu/GET_TRANSFER_LISTS';
export const SET_INITIAL_TRANSFER_MENUS_VISIBLE_STATE =
  'app/TransferMenu/SET_INITIAL_TRANSFER_MENUS_VISIBLE_STATE';
export const UPDATE_QUEUES_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_QUEUES_LIST_VISIBLE_STATE';
export const UPDATE_AGENTS_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_AGENTS_LIST_VISIBLE_STATE';
export const UPDATE_TRANSFER_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_TRANSFER_LIST_VISIBLE_STATE';
