// Redux constants

export const SET_RESOURCE_CAPACITY = 'app/TransferMenu/SET_RESOURCE_CAPACITY';
export const SET_USERS = 'app/TransferMenu/SET_USERS';
export const SET_QUEUES_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_QUEUES_LIST_VISIBLE_STATE';
export const SET_AGENTS_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_AGENTS_LIST_VISIBLE_STATE';
export const SET_TRANSFER_SEARCH_INPUT =
  'app/TransferMenu/SET_TRANSFER_SEARCH_INPUT';
export const SET_FOCUSED_TRANSFER_ITEM_INDEX =
  'app/TransferMenu/SET_FOCUSED_TRANSFER_ITEM_INDEX';
export const SET_TRANSFER_TAB_INDEX = 'app/TransferMenu/SET_TRANSFER_TAB_INDEX';
export const SET_SHOW_TRANSFER_DIAL_PAD =
  'app/TransferMenu/SET_SHOW_TRANSFER_DIAL_PAD';
export const SET_USER_ASSIGNED_TRANSFER_LISTS =
  'app/TransferMenu/SET_USER_ASSIGNED_TRANSFER_LISTS';
export const SET_USER_ASSIGNED_TRANSFER_LISTS_LOADING_STATE =
  'app/TransferMenu/SET_USER_ASSIGNED_TRANSFER_LISTS_LOADING_STATE';
export const SET_USER_ASSIGNED_TRANSFER_LIST_VISIBLE_STATE =
  'app/TransferMenu/SET_USER_ASSIGNED_TRANSFER_LIST_VISIBLE_STATE';
export const SET_VISIBLE_STATE_OF_ALL_USER_ASSIGNED_TRANSFER_LISTS =
  'app/TransferMenu/SET_VISIBLE_STATE_OF_ALL_USER_ASSIGNED_TRANSFER_LISTS';

// Saga constants
export const SET_INITIAL_TRANSFER_MENUS_VISIBLE_STATE =
  'app/TransferMenu/SET_INITIAL_TRANSFER_MENUS_VISIBLE_STATE';
export const UPDATE_QUEUES_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_QUEUES_LIST_VISIBLE_STATE';
export const UPDATE_AGENTS_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_AGENTS_LIST_VISIBLE_STATE';
export const TEAR_DOWN_TRANSFER_MENU_STATES =
  'app/TransferMenu/TEAR_DOWN_TRANSFER_MENU_STATES';
export const TRANSFER_INTERACTION = 'app/TransferMenu/TRANSFER_INTERACTION';
export const UPDATE_USER_ASSIGNED_TRANSFER_LISTS =
  'app/TransferMenu/UPDATE_USER_ASSIGNED_TRANSFER_LISTS';
export const UPDATE_USER_ASSIGNED_TRANSFER_LIST_VISIBLE_STATE =
  'app/TransferMenu/UPDATE_USER_ASSIGNED_TRANSFER_LIST_VISIBLE_STATE';
export const UPDATE_VISIBLE_STATE_OF_ALL_USER_ASSIGNED_TRANSFER_LISTS =
  'app/TransferMenu/UPDATE_VISIBLE_STATE_OF_ALL_USER_ASSIGNED_TRANSFER_LISTS';
