const requiredPermissions = [
  'CONTACTS_CREATE',
  'CONTACTS_UPDATE',
  'CONTACTS_READ',
  'CONTACTS_ATTRIBUTES_READ',
  'CONTACTS_LAYOUTS_READ',
  'CONTACTS_ASSIGN_INTERACTION',
  'CONTACTS_INTERACTION_HISTORY_READ',
  'ARTIFACTS_CREATE_ALL',
];

export default requiredPermissions;
