/*
 * Copyright © 2015-2017 Serenova, LLC. All rights reserved.
 */

/*
 *
 * AgentTranferMenu constants
 *
 */

// Redux constants
export const SET_AGENTS_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/SET_AGENTS_TRANSFER_MENU_PREFERENCE';

//  Redux Queues Constants
export const SET_SHOW_QUEUES_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/SET_SHOW_QUEUES_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_SELECTED_QUEUE_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_SELECTED_QUEUE_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_ALL_SELECTED_QUEUES_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_ALL_SELECTED_QUEUES_TRANSFER_MENU_PREFERENCE';

//  Redux Transfer Lists Constants
export const SET_SHOW_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/SET_SHOW_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_SELECTED_TRANSFER_LIST_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_SELECTED_TRANSFER_LIST_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_ALL_SELECTED_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_ALL_SELECTED_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE';

// Saga Constants
export const INITIALIZE_TRANSFER_MENU_PREFERENCES =
  'app/AgentTransferMenuPreferenceMenu/INITIALIZE_TRANSFER_MENU_PREFERENCES';
export const TOGGLE_AGENTS_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_AGENTS_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_SHOW_QUEUES_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_SHOW_QUEUES_TRANSFER_MENU_PREFERENCE';
export const TOGGLE_SHOW_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE =
  'app/AgentTransferMenuPreferenceMenu/TOGGLE_SHOW_TRANSFER_LISTS_TRANSFER_MENU_PREFERENCE';
